---

name: ci

on:
  push:
  schedule:
    - cron: "0 20 * * *" # every day at 8:00 pm UTC


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - name: Test
        run: go test -v ./...


